name: Respond to /cypress

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  respond:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'cypress')
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello 👋
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            👋 Hello from Cypress!
