name: Respond to /cypress Comment

on:
  issue_comment:
    types: [created]

jobs:
  respond:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Required to post comments
    steps:
      - name: Reply if comment includes "cypress"
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          ISSUE_URL="${{ github.event.comment.issue_url }}"
          echo "Comment body: $COMMENT_BODY"

          if [[ "$COMMENT_BODY" =~ cypress ]]; then
            echo "✅ Posting reply to comment..."

            curl -s -X POST "$ISSUE_URL/comments" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              -d '{"body":"👋 Hello from Cypress!"}'
          else
            echo "No 'cypress' keyword found — skipping reply."
          fi
