name: Respond to /cypress Comment

on:
  issue_comment:
    types: [created]

jobs:
  respond:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Required to post comments
    steps:
      - name: Respond with Hello 👋
        if: contains(github.event.comment.body, 'cypress')
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            👋 Hello from Cypress!

